namespace WorldSim.Runtime.Diagnostics;

public sealed record ScenarioWave9TimelineSnapshot(
    string Wave9Scenario,
    string EvidenceKind,
    string TimelineSemantics,
    int ActiveCampaigns,
    int ActiveArmies,
    int TotalArmyMembers,
    string SupplySourceMode,
    int MemberInventoryConsumed,
    int RationPoolConsumed,
    int CampaignForageAttempts,
    int CampaignForageFoodGained,
    string CampaignPhase,
    int CampaignAssemblingTicks,
    int CampaignMarchingTicks,
    int CampaignEncounterTicks,
    int CampaignRouteProgress,
    int CampaignEncounterCount)
{
    public static ScenarioWave9TimelineSnapshot Empty { get; } = new(
        Wave9Scenario: "none",
        EvidenceKind: "not_configured",
        TimelineSemantics: "not_sampled",
        ActiveCampaigns: 0,
        ActiveArmies: 0,
        TotalArmyMembers: 0,
        SupplySourceMode: "none",
        MemberInventoryConsumed: 0,
        RationPoolConsumed: 0,
        CampaignForageAttempts: 0,
        CampaignForageFoodGained: 0,
        CampaignPhase: "none",
        CampaignAssemblingTicks: 0,
        CampaignMarchingTicks: 0,
        CampaignEncounterTicks: 0,
        CampaignRouteProgress: 0,
        CampaignEncounterCount: 0);
}

public sealed record ScenarioWave9TelemetrySnapshot(
    string Wave9Scenario,
    string EvidenceKind,
    string TimelineSemantics,
    int ActiveCampaigns,
    int ActiveArmies,
    int TotalArmyMembers,
    int TotalRationPoolFood,
    int CampaignLaunches,
    int AssemblyStartedCount,
    int AssemblyCompletedCount,
    int MarchStartedCount,
    int MarchCompletedCount,
    int CampaignsReturnedOrAborted,
    string SupplySourceMode,
    int MemberInventoryConsumed,
    int RationPoolConsumed,
    int CarriedInventorySupplyTicks,
    int RationPoolSupplyTicks,
    int LowSupplyTicks,
    int OutOfSupplyTicks,
    int SupplyAttritionEvents,
    int SupplyRoutingEvents,
    int CarrierAssignments,
    int CarrierDeliveries,
    int ResupplyDelivered,
    int CampaignForageAttempts,
    int CampaignForageSuccesses,
    int CampaignForageFoodGained,
    int CampaignForageCapReached,
    string CampaignPhase,
    int CampaignAssemblingTicks,
    int CampaignMarchingTicks,
    int CampaignEncounterTicks,
    int CampaignRouteProgress,
    int CampaignEncounterCount,
    int PeakMarchDistance)
{
    public static ScenarioWave9TelemetrySnapshot Empty { get; } = new(
        Wave9Scenario: "none",
        EvidenceKind: "not_configured",
        TimelineSemantics: "not_sampled",
        ActiveCampaigns: 0,
        ActiveArmies: 0,
        TotalArmyMembers: 0,
        TotalRationPoolFood: 0,
        CampaignLaunches: 0,
        AssemblyStartedCount: 0,
        AssemblyCompletedCount: 0,
        MarchStartedCount: 0,
        MarchCompletedCount: 0,
        CampaignsReturnedOrAborted: 0,
        SupplySourceMode: "none",
        MemberInventoryConsumed: 0,
        RationPoolConsumed: 0,
        CarriedInventorySupplyTicks: 0,
        RationPoolSupplyTicks: 0,
        LowSupplyTicks: 0,
        OutOfSupplyTicks: 0,
        SupplyAttritionEvents: 0,
        SupplyRoutingEvents: 0,
        CarrierAssignments: 0,
        CarrierDeliveries: 0,
        ResupplyDelivered: 0,
        CampaignForageAttempts: 0,
        CampaignForageSuccesses: 0,
        CampaignForageFoodGained: 0,
        CampaignForageCapReached: 0,
        CampaignPhase: "none",
        CampaignAssemblingTicks: 0,
        CampaignMarchingTicks: 0,
        CampaignEncounterTicks: 0,
        CampaignRouteProgress: 0,
        CampaignEncounterCount: 0,
        PeakMarchDistance: 0);

    public ScenarioWave9TelemetrySnapshot AsDeterministicProbe()
        => this with
        {
            EvidenceKind = "deterministic_probe",
            TimelineSemantics = "not_tick_sampled"
        };
}
